### ISSUE TITLE
Quick Help With etching

### ISSUE THREAD

**Issue by karmabadger** [0xPhaze/paradigm-ctf-2021-foundry#1]
Was UniswapRouter02 also etched in this project?

**Comment by 0xPhaze** [comment]
I just added the bytecode for the routers.
Just ran

```
git clone https://github.com/Uniswap/v2-periphery
cd v2-periphery
yarn && yarn compile
```

**Comment by karmabadger** [comment]
> I just added the bytecode for the routers. Just ran
> 
> ```
> git clone https://github.com/Uniswap/v2-periphery
> cd v2-periphery
> yarn && yarn compile
> ```

thanks for the help ser. if I may ask, how did you obtain the runtime code and the creation code? creation code is just the bytecode in the json artifact right? what abotu the runtime code?

**Comment by 0xPhaze** [comment]
nw, yes, creation code is under "bytecode" and runtime code should be "runtimeCode" (or similar).
